[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datascrape"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = ["click"]

[tool.setuptools]
py-modules = []
