[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "website"
version = "1.0.0"
dependencies = ["Flask"]
requires-python = ">=3.10"

[tool.setuptools]
py-modules = []
