INSERT INTO teams (id, location, name, abbreviation) VALUES
    (1, 'New York', 'Voyagers', 'nyv'),
    (2, 'Outer Banks', 'Aviators', 'obx'),
    (3, 'Provdence', 'Crabs', 'pro'),
    (40, 'Buffalo', 'Surge', 'buf'),
    (9, 'San Antonio', 'Sloths', 'sas'),
    (11, 'Vancouver', 'Vandals', 'van'),
    (25, 'Boise', 'Raptors', 'boi'),
    (37, 'Maui', 'Makos', 'mau'),
    (36, 'Indianapolis', 'Apex', 'ind'),
    (24, 'Lunar Base', 'Space Rangers', 'lun'),
    (27, 'Nashville', 'Stars', 'nsh'),
    (33, 'Detroit', 'Demons', 'det'),
    (26, 'Cancun', 'Toros', 'cun'),
    (32, 'New Orleans', 'Rougarous', 'no'),
    (10, 'Death Valley', 'Scorpions', 'dvs'),
    (41, 'Seattle', 'Sea Serpents', 'sea'),
    (16, 'Anchorage', 'Wheelers', 'anc'),
    (19, 'Amarillo', 'Armadillos', 'ama'),
    (28, 'Kansas City', 'Hepcats', 'kc'),
    (30, 'California', 'Firehawks', 'cal'),
    (38, 'Brew City', 'Bears', 'bcb'),
    (18, 'State College', 'Swift Steeds', 'scss'),
    (17, 'Florida', 'Flamingos', 'fla'),
    (29, 'Puerto Rico', 'Ranas', 'pr'),
    (31, 'Chicago', 'Kingpins', 'chi'),
    (39, 'Louisville', 'Lemurs', 'll'),
    (0, 'Free', 'Agents', 'fa');
