CREATE TABLE teams (
    id PRIMARY KEY NOT NULL,
    location VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    abbreviation VARCHAR(4) UNIQUE NOT NULL
);

CREATE TABLE players (
    id PRIMARY KEY NOT NULL,
    team_id REFERENCES teams(id) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    firstname VARCHAR(255),
    nickname VARCHAR(255),
    number INTEGER NOT NULL,
    birthYear INTEGER NOT NULL,
    birthMonth INTEGER NOT NULL,
    birthDay INTEGER NOT NULL,
    birthCountry VARCHAR(255) NOT NULL,
    birthCity VARCHAR(255) NOT NULL,
    height INTEGER NOT NULL,
    weight INTEGER NOT NULL,

    position VARCHAR(255) NOT NULL,

    bats VARCHAR(255) NOT NULL,
    throws VARCHAR(255) NOT NULL,
    gbType VARCHAR(255) NOT NULL,
    fbType VARCHAR(255) NOT NULL,
    armSlot VARCHAR(255) NOT NULL,

    babipL INTEGER NOT NULL,
    babipR INTEGER NOT NULL,
    babipPot INTEGER NOT NULL,
    avoidkL INTEGER NOT NULL,
    avoidkR INTEGER NOT NULL,
    avoidkPot INTEGER NOT NULL,
    powerL INTEGER NOT NULL,
    powerR INTEGER NOT NULL,
    powerPot INTEGER NOT NULL,
    gapL INTEGER NOT NULL,
    gapR INTEGER NOT NULL,
    gapPot INTEGER NOT NULL,
    eyeL INTEGER NOT NULL,
    eyeR INTEGER NOT NULL,
    eyePot INTEGER NOT NULL,
    speed INTEGER NOT NULL,
    run INTEGER NOT NULL,
    steal INTEGER NOT NULL,
    buntSac INTEGER NOT NULL,
    buntHit INTEGER NOT NULL,

    movementL INTEGER NOT NULL,
    movementR INTEGER NOT NULL,
    movementPot INTEGER NOT NULL,
    controlL INTEGER NOT NULL,
    controlR INTEGER NOT NULL,
    controlPot INTEGER NOT NULL,
    stamina INTEGER NOT NULL,
    holdRunners INTEGER NOT NULL,
    gbRate INTEGER NOT NULL,
    velocity VARCHAR(255) NOT NULL,

    rangeIf INTEGER NOT NULL,
    rangeOf INTEGER NOT NULL,
    errorIf INTEGER NOT NULL,
    errorOf INTEGER NOT NULL,
    armIf INTEGER NOT NULL,
    armOf INTEGER NOT NULL,
    armC INTEGER NOT NULL,
    doublePlay INTEGER NOT NULL,
    abilityC INTEGER NOT NULL,

    expP INTEGER NOT NULL,
    expC INTEGER NOT NULL,
    exp1B INTEGER NOT NULL,
    exp2B INTEGER NOT NULL,
    exp3B INTEGER NOT NULL,
    expSS INTEGER NOT NULL,
    expLF INTEGER NOT NULL,
    expCF INTEGER NOT NULL,
    expRF INTEGER NOT NULL,

    stuffSplit FLOAT NOT NULL,
    fastball INTEGER NOT NULL,
    fastballPot INTEGER NOT NULL,
    slider INTEGER NOT NULL,
    sliderPot INTEGER NOT NULL,
    curve INTEGER NOT NULL,
    curvePot INTEGER NOT NULL,
    change INTEGER NOT NULL,
    changePot INTEGER NOT NULL,
    cutter INTEGER NOT NULL,
    cutterPot INTEGER NOT NULL,
    sinker INTEGER NOT NULL,
    sinkerPot INTEGER NOT NULL,
    splitter INTEGER NOT NULL,
    splitterPot INTEGER NOT NULL,
    fork INTEGER NOT NULL,
    forkPot INTEGER NOT NULL,
    screw INTEGER NOT NULL,
    screwPot INTEGER NOT NULL,
    circle INTEGER NOT NULL,
    circlePot INTEGER NOT NULL,
    kCurve INTEGER NOT NULL,
    kCurvePot INTEGER NOT NULL,
    knuckle INTEGER NOT NULL,
    knucklePot INTEGER NOT NULL
);
